<ShortPreview>
    #on_press: app.root.current = 'login'
    MDBoxLayout:
        orientation: 'vertical'
        pos: root.pos
        size: self.parent.size
        md_bg_color: .9, .9, .9, 1
        spacing: dp(5)

        Image:
            id: thumbnail
            source: 'images/thumbnail.jpg'
            size: self.size
            size_hint: 1, .8

        MDLabel:
            id: title
            text: 'Video Title'
            size_hint: 1, .2
            font_size: dp(20)

